App\Entity\Item:
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 10
        content:
            type: text
        created:
            type: datetime_immutable