version: "3"

services:
  web:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./../back:/srv
      - ./nginx/back.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
#    image: php:7.2-fpm
    build:
      context: './../'
      dockerfile: 'docker/php/Dockerfile'
      args:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${COMPOSER_GITHUB_TOKEN}"}}'
    volumes:
        - ./../back:/app

  db:
    image: postgres
    restart: always
    volumes:
        - "./var/db:/var/lib/postgresql"
    environment:
      POSTGRES_DATABASE: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}